### PR TITLE
Add article about how to extend Application and Activity

### PR DESCRIPTION
**Pull request by atanasovg**

### CODE REVIEW

**Comment by atanasovg** [comment]
ping @NativeScript/android-runtime

**Comment by Pip3r4o** [comment]
Very informative and thorough :+1:

**Comment by Plamen5kov** [comment]
Looks great, maybe it's a good idea to add an example repo. :+1:

**Comment by atanasovg** [comment]
@Plamen5kov There is such repo, it is just still private. I will update the article with a link.

**Pull request merged**
